import { Inter } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-background', inter.variable)}>{children}</body>
    </html>
  );
}
